# Generated by Django 4.2.7 on 2023-12-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='empno',
            new_name='deptno',
        ),
    ]
